// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cox_suffstat
Rcpp::List cox_suffstat(const arma::mat& X, const arma::vec& eta, const arma::vec& time, const arma::ivec& status, int n_threads);
RcppExport SEXP _SuSiE4I_cox_suffstat(SEXP XSEXP, SEXP etaSEXP, SEXP timeSEXP, SEXP statusSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type time(timeSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type status(statusSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cox_suffstat(X, eta, time, status, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// blockwise_crossprod
arma::mat blockwise_crossprod(const arma::mat& X, int n_threads, int block_size);
RcppExport SEXP _SuSiE4I_blockwise_crossprod(SEXP XSEXP, SEXP n_threadsSEXP, SEXP block_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type block_size(block_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(blockwise_crossprod(X, n_threads, block_size));
    return rcpp_result_gen;
END_RCPP
}
// blockwise_crossprod2
arma::mat blockwise_crossprod2(const arma::mat& X, const arma::mat& Z, int n_threads, int block_size);
RcppExport SEXP _SuSiE4I_blockwise_crossprod2(SEXP XSEXP, SEXP ZSEXP, SEXP n_threadsSEXP, SEXP block_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type block_size(block_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(blockwise_crossprod2(X, Z, n_threads, block_size));
    return rcpp_result_gen;
END_RCPP
}
// large_scale
arma::mat large_scale(arma::mat X, bool center, bool scale, int n_threads);
RcppExport SEXP _SuSiE4I_large_scale(SEXP XSEXP, SEXP centerSEXP, SEXP scaleSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< bool >::type center(centerSEXP);
    Rcpp::traits::input_parameter< bool >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(large_scale(X, center, scale, n_threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SuSiE4I_cox_suffstat", (DL_FUNC) &_SuSiE4I_cox_suffstat, 5},
    {"_SuSiE4I_blockwise_crossprod", (DL_FUNC) &_SuSiE4I_blockwise_crossprod, 3},
    {"_SuSiE4I_blockwise_crossprod2", (DL_FUNC) &_SuSiE4I_blockwise_crossprod2, 4},
    {"_SuSiE4I_large_scale", (DL_FUNC) &_SuSiE4I_large_scale, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_SuSiE4I(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
